language: node_js
node_js:
- '8'
env:
  global:
  #- USER="IgnacioPasamontes"
  #- EMAIL="ignacio.pasamontes@upf.edu"
  - ORG="phi-grib"
  - REPO="DjangoAPI"
  #- FILES="./dist/frontend/*"
  - GH_REPO="github.com/${ORG}/${REPO}.git"
  - secure: "kQGk+VUp6a9hGH+NmeZqesNCpuZ/EzB88//6K2wm3bHlipqnqVVDF5BSmIx175+dKgYcVhVqlayP4I6v8f2y3j6kCDxIN48S8f0ekxjcbmJWUuvODMsbp6TxxAwx5rgvNCA1x8otAlTyPuRi6sFM17Gri5GR0L/xWZZZhTIWCngFrpfDFNw2yb007fqsaP4u99PiOxvCOhoeMkq4vvNkMIQ3W8kfLjmwNv0vV5HftrdoIeCMzWnSv8T9MrGSq6a6XwwNQ+Kb2vCRCE2+ksz6QteqWQnsZYxF8aGhoAFP4fXfI8poUjCDhyfDf8f+rPEmI3k1+CUKX/0blUUxhsGw8bHpkGL9QipzgstG07V2QJp3h0OEbsq7KS+hbGZVrRnRGpWHgrjND43lQrJxIb4Szw/SBcs66BaVk9D3TIbGhW+ibN4F+vjqFGIm1FhmhiiVHLxW9v8GbZJt36xeRCu6Daul5f8aHf2wihAZVSvKoSCu4Uz69JxQYGi7TNzyEWZgLR4SLzM/UNx+5Aj/2dIEQ/NE7NN5x4MLDbxjJE73/U7c+GEfl+svvu7lYN7Cv2NFyh+7MaV35McdMtHfHrbMVph1Urm4GqJryYadAUdrIkonzVYH+PeS44LGT/D9ls5IWIjXaxItEkz56x09LFrF+4SMxvn72vOl6twTYLvN6VQ="

 
efore_script:
- npm install -g @angular/cli
script:
- ng build --prod --aot  --output-hashing none
after_success:
- MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- git clone https://github.com/phi-grib/DjangoAPI.git
- pwd
- ls -l
- rm -rfv ./DjangoAPI/static/*
- cd DjangoAPI/
- git remote
- git config user.email ignacio.pasamontes@upf.edu
- git config user.name IgnacioPasamontes
- git rm static/*
- git commit -m 'BUILD:Remove statics'
- git push "https://travis@${GH_REPO}"


#ADD static
- mkdir static
- mv -f ../dist/frontend/* ./static
- git remote
- git config user.email ignacio.pasamontes@upf.edu
- git config user.name IgnacioPasamontes
- git add static/*
- git commit -m 'BUILD:ADD statics'
- git push "https://travis@${GH_REPO}"