language: node_js
node_js:
- '8'
env:
  global:
  - ORG="phi-grib"
  - REPO="DjangoAPI"
  - GH_REPO="github.com/${ORG}/${REPO}.git"
  - secure: gVT01TOvSWqYO704gpZdM1Dd7G6hDrpJ8Ah/MR1uZD7LxTAx3UtT5fkiszxpS7RkVxGzQfmULeiUyP9lZIsvas7lzUxoKpHFxgUbB9U56zkuqmGuq2pSprogWzuDrLd8cw3KoB8RCV/KMCTx9KaSYCSc6d9K6woLoyJtSdQMQDkuQBVYwUW8oeVKrt1Nd7fyRy27sUzXMEBhnZ0jKtU5gvPMvk+sLwnML5rHgLlbOWyeM5akSgLm5/g1RhkEgGNCHGCtkucnK7qU4LL+d4qSJkX6q+N/bRSL2W2YX8mgbnfzC5+2ox+MADemwbI2GT5dnm796Ic8X7+CU4qjMFFQ0hgVas4VIJH7sjN/1rYQQErbJ9lQq2zYkWUmjL+eQt0Q6bK9pmJvz20QBwKhYf19TRSLUMpWn2cE1zEvUeChLOtcxKb/4CwU7youdBphCr/Hve1uaE2Vamr4eAtom1EtEirtERABAKsYeL9pd2ncdODiMrI2reqpOggOl1AwNHqAbsg9eKoNC4ap4iv2sbxrTpD80Oh3XEQVjecjaM1XvylzbpIU4Al9y1uGCqWv3NONkS3+EkOrPkX7c6VBOooikm8GFBV25+BJ/BqgDk8r9c8Jocp+x5dCGZGRs8ROY5ymFc1g6xOC2jxfGrmVmVnPvYM6kI/9p6Rw2+EVi+yLIpU=
before_script:
- npm install -g @angular/cli
script:
- ng build --prod --aot --output-hashing none
after_success:
- MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- git clone https://github.com/phi-grib/DjangoAPI.git
- pwd
- ls -l
- rm -rfv ./DjangoAPI/static/*
- cd DjangoAPI/
- git remote
- git config --global user.email "ignacio.pasamontes@upf.edu"
- git config --global user.name "IgnacioPasamontes"
- git rm static/*
- touch file.txt
- git add file.txt
- git push "https://${GH_TOKEN}@${GH_REPO}"
