language:  node_js
node_js:
  - "8"
env:
  global:
  - USER="IgnacioPasamontes"
  - EMAIL="ignacio.pasamontes@upf.edu"
  - ORG = "phi-grib"
  - REPO="DjangoAPI"
  - FILES="./dist/frontend/*"
  - GH_REPO="github.com/${ORG}/${REPO}.git"

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot  --output-hashing none
  #- ng test
after_success:
  
  #REMOVE static

  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - echo ${MESSAGE}
  - git clone https://${GH_REPO}
  - pwd
  - ls -l
  - rm -rfv ./DjangoAPI/static/*
  - cd DjangoAPI/
  - git rm static/*
  - git remote
  - git config user.email ${EMAIL}
  - git config user.name ${USER}
  - git commit -m 'BUILD:Remove statics' 
  - git push "https://${SOMVAR}@${GH_REPO}" master > /dev/null 2>&1Travis token name